---
development:
  sessions:
    default:
      database: tng-catalogue
      hosts:
      - mongo:27017
production:
  sessions:
    default:
      database: tng-catalogue
      hosts:
      - mongo:27017
test:
  sessions:
    default:
      database: tng-catalogue
      hosts:
      - mongo:27017
